Add GitHub Secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,6 +21,9 @@ jobs:
 
     name: Test on ${{ matrix.os }} with Node ${{ matrix.node-version }}
 
+    env:
+      API_KEY: ${{ secrets.API_KEY }}
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -29,6 +32,16 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
+
+      - name: Check API key
+        shell: bash
+        run: |
+          if [ -n "$API_KEY" ]; then
+            echo "API key is available"
+          else
+            echo "API key is missing"
+            exit 1
+          fi      
 
       - name: Check Node version
         run: node --version
